/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Switch_1_Control_aliases.h"
#include "Switch_1_Control.h"
#include "Switch_2_Control_aliases.h"
#include "Switch_2_Control.h"
#include "Switch_15_Control_aliases.h"
#include "Switch_15_Control.h"
#include "Switch_16_Control_aliases.h"
#include "Switch_16_Control.h"
#include "Switch_17_Control_aliases.h"
#include "Switch_17_Control.h"
#include "Switch_18_Control_aliases.h"
#include "Switch_18_Control.h"
#include "UART.h"
#include "EEPROM.h"
#include "ZeroGasOut_aliases.h"
#include "ZeroGasOut.h"
#include "Switch_3_Control_aliases.h"
#include "Switch_3_Control.h"
#include "Switch_4_Control_aliases.h"
#include "Switch_4_Control.h"
#include "Switch_5_Control_aliases.h"
#include "Switch_5_Control.h"
#include "Switch_6_Control_aliases.h"
#include "Switch_6_Control.h"
#include "Switch_7_Control_aliases.h"
#include "Switch_7_Control.h"
#include "Switch_8_Control_aliases.h"
#include "Switch_8_Control.h"
#include "Switch_9_Control_aliases.h"
#include "Switch_9_Control.h"
#include "Switch_10_Control_aliases.h"
#include "Switch_10_Control.h"
#include "Switch_11_Control_aliases.h"
#include "Switch_11_Control.h"
#include "Switch_12_Control_aliases.h"
#include "Switch_12_Control.h"
#include "Switch_13_Control_aliases.h"
#include "Switch_13_Control.h"
#include "Switch_14_Control_aliases.h"
#include "Switch_14_Control.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

